# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
     
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Runs a single command using the runners shell
      - name: download tinycc
        run: |
          Invoke-WebRequest -OutFile tinycc.zip -Uri http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.27-win64-bin.zip
          Expand-Archive -LiteralPath tinycc.zip -DestinationPath .\

      - name: download Lua source
        run: |
          Invoke-WebRequest -OutFile lua54.tar.gz -Uri https://www.lua.org/ftp/lua-5.4.4.tar.gz
      - name: extract Lua source
        run: |
          python3 extract_tar_gz.py lua54.tar.gz
      - name: compile Lua
        run: |
          Remove-Item lua-5.4.4\src\luac.c
          tcc\tcc.exe -o lua.exe lua-5.5.5\src\*.c
      - name: run lua
        run: |
          lua.exe -e "print('greetings from Lua')"
          
          


